import React from "react";
import RecommendationsClient from "@/app/components/recommendations/RecommendationsClient";
import { getRecommendations } from "./actions";

export const metadata = {
  title: "Recommendations | NutJob",
  description: "AI-powered agronomic insights and action items",
};

export default async function RecommendationsPage() {
  const recommendations = await getRecommendations();

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight">
          Recommendations
        </h1>
        <p className="text-slate-500 dark:text-slate-400 mt-1">
          Review and act on prioritized agronomic insights generated by the NutJob AI engine.
        </p>
      </div>

      <RecommendationsClient initialRecommendations={recommendations as any} />
    </div>
  );
}
