import React from "react";
import RecommendationsClient from "@/app/components/recommendations/RecommendationsClient";
import { getRecommendations } from "./actions";

export const metadata = {
  title: "Recommendations | NutJob",
  description: "AI-powered agronomic insights and action items",
};

import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";

export default async function RecommendationsPage() {
  const supabase = await createClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    redirect("/login");
  }

  const { data: profile } = await supabase
    .from("user_profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (profile?.role === "worker") {
    redirect("/dashboard?error=Unauthorized");
  }

  const recommendations = await getRecommendations();

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight">
          Recommendations
        </h1>
        <p className="text-slate-500 dark:text-slate-400 mt-1">
          Review and act on prioritized agronomic insights generated by the NutJob AI engine.
        </p>
      </div>

      {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
      <RecommendationsClient initialRecommendations={recommendations as any} />
    </div>
  );
}
